name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Check formatting and lint errors
        run: yarn ci:check
      - name: Run tests
        run: yarn test
